name: stack_overflow
version: 1.0.0
config-version: 2

profile: 'BIGQUERY'

model-paths: ["models"]
test-paths: ["tests"]

models:
  stack_overflow:
    warehouse:
      materialized: table
      schema: warehouse
    datamart:
      materialized: table
      schema: datamart

on-run-start:
  - "{{ log('Starting dbt run', info=True) }}"

on-run-end:
  - "{{ log('Ending dbt run', info=True) }}"
