version: 2

sources:
  - name: stackoverflow_source
    database: bigquery-public-data
    schema: stackoverflow
    tables:
      - name: posts_questions
        description: "Post questions source from Big Query public data"