version: 2

sources:
  - name: stackoverflow_source
    database: bigquery-public-data
    schema: stackoverflow
    tables:
      - name: users
        description: "Stackoverflow users source from BigQuery public data"
      - name: posts_questions
        description: "Stackoverflow post questions source from BigQuery public data"
      - name: posts_answers
        description: "Stackoverflow post answers source from BigQuery public data"
